package rules

import com.sample.model.*;

/*
rule "bar 4 simptoma"
salience 2
    when
        $b: Bolest(grupa == "prva", $blist: simptomi)
        $s: Symptoms($slist: simptomi)
    then
        System.out.println($b.getNaziv());

end
*/

rule "svi simptomi"
salience 1
    when
    	$slist: Symptom()
        $b: Bolest(grupa == "prva" || grupa == "druga", $blist: simptomi)
		$k: String() from $blist
    then
        System.out.println($b.getNaziv());

end

